<p>
In Europe, the origins of the war are closely tied to the rise of fascism, especially in Nazi Germany. A discussion of how the Nazis came to power is a requisite in this context.

The origins of the Second World War are generally viewed as being traced back to the First World War (1914-1918). In that war Germany under the ultra-nationalistic Kaiser Wilhelm II along with its allies, had been defeated by a combination of the United Kingdom, United States, France, Russia and others. The war was directly blamed by the victors on the miltant nationalism of the Kaiser's Germany; it was Germany that effectively started the war with an attack on France through Belgium. France, which had suffered a previous defeat at the hands of Prussia (a state that merged one year later with others to form Germany) in the Franco-Prussian War in 1870, demanded revenge for its financial devastation during the First World War (and its humiliation in the earlier war) ensured that the various peace treaties, specifically the Treaty of Versailles imposed tough financial reparations and restrictions on Germany.

A new democratic German republic, known as the Weimar Republic, came into being. After some success it was hit by hyperinflation and other serious economic problems. Right wing nationalist elements under a variety of movements, but most notably the Nazi Party of Adolf Hitler, sought to blame Germany's "humiliating" status on the harshness of the post-war settlement, on the weakness of democratic government, and on the Jews, whom it claimed possessed a financial stranglehold on Germany. Hitler was appointed Reichskanzler (Chancellor) on January 30, 1933, by the aged President von Hindenburg. Hitler's government exercised much of its power through the special emergency powers possessed by the President under the constitution.

These powers enabled a government with the President's powers to effectively bypass the Reichstag (federal parliament). Under a further disastrous clause in the Weimar constitution when the President died, his office was temporarily assumed by the Chancellor. As a result, when Hindenburg died, the immense powers of the presidency fell into the hands of Adolf Hitler. Through the possession of those powers and an Enabling Act that allowed the nazi government to bypass and ignore the constitution, Hitler ensured his possession of the presidential powers became permanent and so gained dictatorial control over Germany.
</p>
